spring.application.name=clinica-mackito

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.jwt.secret=${JWT_SECRET}

app.bootstrap.admin.email=${ADMIN_INITIAL_EMAIL:}
app.bootstrap.admin.password=${ADMIN_INITIAL_PASSWORD:}
